name: Build and Test

on:
  workflow_call:
    inputs:
      qc-max-success:
        description: Maximum number of successful tests for QuickCheck
        required: false
        type: number
        default: 10000
  workflow_dispatch:
    inputs:
      qc-max-success:
        description: Maximum number of successful tests for QuickCheck
        required: false
        type: number
        default: 10000
  pull_request:
  push:
    branches: [main, master]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-haskell:
    uses: nikita-volkov/haskell-hackage-lib-github-actions-workflows/.github/workflows/build.yaml@v4
    secrets: inherit
    with:
      ghc: "9.12"
      skip-doctest: true
      skip-benchmarks: true
      test-options: --qc-max-success=${{ inputs.qc-max-success }}
